import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { relative, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const scriptsRoot = resolve(root, 'packages/gameplay/src/scripts');
const output = resolve(root, 'packages/gameplay/src/generated-registry.ts');

async function files(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map((entry) => entry.isDirectory() ? files(resolve(directory, entry.name)) : [resolve(directory, entry.name)]));
  return nested.flat().filter((file) => file.endsWith('.ts')).sort();
}

const sources = await files(scriptsRoot);
const entries = await Promise.all(sources.map(async (file, index) => {
  const normalized = (await readFile(file, 'utf8')).replace(/\r\n/g, '\n');
  const parts = relative(scriptsRoot, file).replace(/\\/g, '/').replace(/\.ts$/, '').split('/');
  const version = parts.pop();
  const id = parts.join('/');
  if (!id || !version) throw new Error(`invalid gameplay script path: ${file}`);
  return { id, version, hash: createHash('sha256').update(normalized, 'utf8').digest('hex'), importName: `script${index}`, importPath: `./scripts/${id}/${version}.ts` };
}));

const text = `/* Generated by pnpm gameplay:generate. Do not edit. */\n` +
  `import { GameplayScriptRegistry } from '@atc/gameplay-sdk';\n` +
  entries.map((entry) => `import ${entry.importName} from '${entry.importPath}';`).join('\n') + '\n\n' +
  `export const gameplayScriptRegistry = new GameplayScriptRegistry([\n` +
  entries.map((entry) => `  { reference: { assetType: 'gameplay-script', assetId: '${entry.id}', version: '${entry.version}', contentHash: '${entry.hash}' }, definition: ${entry.importName} },`).join('\n') +
  `\n]);\n`;

if (process.argv.includes('--check')) {
  const current = await readFile(output, 'utf8').catch(() => '');
  if (current.replace(/\r\n/g, '\n') !== text) throw new Error('generated gameplay registry is stale; run pnpm gameplay:generate');
} else {
  await writeFile(output, text);
  console.log(`generated ${entries.length} gameplay scripts`);
}
