/* Generated by pnpm gameplay:generate. Do not edit. */
import { GameplayScriptRegistry } from '@atc/gameplay-sdk';
import script0 from './scripts/health/1.0.0.ts';
import script1 from './scripts/stamina/1.0.0.ts';

export const gameplayScriptRegistry = new GameplayScriptRegistry([
  { reference: { assetType: 'gameplay-script', assetId: 'health', version: '1.0.0', contentHash: '4a0bcb103eed8f88870ab2a025966f51f0ec51848cdc843b361571236aab91c7' }, definition: script0 },
  { reference: { assetType: 'gameplay-script', assetId: 'stamina', version: '1.0.0', contentHash: 'fd9d5256dbdf0ca73be54db0250e7c335a25f914b4bcd9b4145b45eb4c9b8cfb' }, definition: script1 },
]);
